name: Auto Update Site

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Trigger rebuild
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Trigger daily rebuild"
          git push
